<?php

namespace Tests\Unit;

use App\Filters\DataFilter;

class FilterTestCase extends \PHPUnit\Framework\TestCase
{
    protected DataFilter $dataFilter;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->dataFilter = new DataFilter();
    }
}
